version: '3.0'

services:
  api:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    expose:
      - 8080
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test_exercise_backend
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test_exercise_backend
volumes:
  postgres_data: